
#ifndef DEF_ULDUAR_H
#define DEF_ULDUAR_H

enum
{
    TYPE_FLAME_LEVIATHAN = 1,
    TYPE_IGNIS,
    TYPE_RAZORSCALE,
    TYPE_XT002,
    TYPE_IRON_COUNCIL,
    TYPE_KOLOGARN,
    TYPE_AURIAYA,
    TYPE_HODIR,
    TYPE_FREYA,
    TYPE_THORIM,
    TYPE_MIMIRON,
    TYPE_VEZAX,
    TYPE_YOGG_SARON,
    TYPE_ALGALON,

    //Hardmodes etc.
    TYPE_HODIR_HARD,
    TYPE_MIMIRON_HARD,
    TYPE_THORIM_HARD,

    TYPE_LEVIATHAN_TP,
    TYPE_XT002_TP,
    TYPE_MIMIRON_TP,

    TYPE_KEEPERS,

    NPC_KOLOGARN = 100,
    NPC_KOLOGARN_RIGHT_ARM,
    NPC_KOLOGARN_LEFT_ARM,
    NPC_STEELBREAKER,
    NPC_MOLGEIM,
    NPC_BRUNDIR,
};


#endif
