
#ifndef DEF_ULDUAR_H
#define DEF_ULDUAR_H

enum
{
    TYPE_FLAME_LEVIATHAN = 1,
    TYPE_IGNIS = 2,
    TYPE_RAZORSCALE = 3,
    TYPE_XT002 = 4,
    TYPE_IRON_COUNCIL = 5,
    TYPE_KOLOGARN = 6,
    TYPE_AURIAYA = 7,
    TYPE_HODIR = 8,
    TYPE_FREYA = 9,
    TYPE_THORIM = 10,
    TYPE_MIMIRON = 11,
    TYPE_VEZAX = 12,
    TYPE_YOGG_SARON = 13,
    TYPE_ALGALON = 14,

    //Hardmodes etc.
    TYPE_HODIR_HARD = 15,
    TYPE_MIMIRON_HARD = 16,
    TYPE_THORIM_HARD = 17,

    TYPE_LEVIATHAN_TP = 18,
    TYPE_XT002_TP = 19,
    TYPE_MIMIRON_TP = 20,



    NPC_STEELBREAKER = 21,
    NPC_MOLGEIM = 22,
    NPC_BRUNDIR = 23,

    TYPE_KEEPERS = 24,

    NPC_KOLOGARN = 25,
    NPC_KOLOGARN_RIGHT_ARM = 26,
    NPC_KOLOGARN_LEFT_ARM = 27,

    GO_KOLOGARN_BRIDGE          = 194232,
    GO_KOLOGARN_LOOT            = 195046,
    GO_KOLOGARN_LOOT_H          = 195047,
    GO_LEVIATHAN_GATE           = 194630

};


#endif
