-- UPDATE `instance_template` SET `script`='instance_halls_of_reflection' WHERE `map`=668;
-- UPDATE `creature_template` SET `ScriptName`='boss_falryn' WHERE `entry`=33112;
-- UPDATE `creature_template` SET `ScriptName`='boss_marwyn' WHERE `entry`=38113;
-- UPDATE `creature_template` SET `ScriptName`='boss_lich_king_fh' WHERE `entry`=37226;
